### ISSUE TITLE
[Question] 1.7.10 Minimaps?

### ISSUE THREAD

**Issue by UeberallGebannt** [turikhay/MapModCompanion#28]
Hello :)
I saw that most minimaps are only supported for version 1.8 and later, is this caused by the minimaps itself or could support be added?

Greetings,
@UeberallGebannt

**Comment by turikhay** [comment]
We target Spigot, which is only available down to 1.8 [[ref]](https://www.spigotmc.org/wiki/buildtools/#1-8).

Other than that I don't see why Xaero's mods wouldn't work with this plugin on 1.7.10, since this version is still being regularly updated. [[1]](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/files/all?filter-game-version=2020709689%3A4449) [[2]](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map/files/all?filter-game-version=2020709689%3A4449)

VoxelMap, on the other hand, probably won't work out of the box.

**Comment by UeberallGebannt** [comment]
Ok, I'm just asking since I use this plugin for my modpack network so that people can have the correct map on the different sub servers. For 1.7 I actually only need Xaero's, but I just wanted to make sure^^
